- app/controllers/invitations_controller.rb
- app/controllers/requests_controller.rb
- app/controllers/sessions_controller.rb
- app/mailers/iuvare_mailer.rb
- app/models/invitation.rb
- app/models/request.rb
- app/models/user.rb
- app/views/devise/sessions/get.json.jbuilder
- app/views/iuvare_mailer/send_invitation.html.erb
- app/views/requests/change_status.json.jbuilder
- app/views/requests/create.json.jbuilder
- app/views/requests/get_pending.json.jbuilder
- config/initializers/state_machine.rb
- config/routes.rb
- spec/controllers/invitations_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- spec/controllers/requests_controller_spec.rb
- spec/factories/requests_factory.rb
- spec/support/devise_helpers.rb
H1.1-T2: Envío de invitaciones de registro (backend) #29979592881817
H1.2-T2: Solicitudes de registro (backend) #30388940153650
H1.3-T2: Responder solicitudes de registro (backend) #30388940153655
Diego
> H1-T9: Servicio para obtener sesión #30243030530059

- app/controllers/users_controller.rb
- app/models/user.rb
Se modifica el query de downlines para obtener todos sin importar por ahora el valor de "active"
Diego
> Corrección de queries

- app/assets/javascripts/app.js
Ahora los controladores de las páginas se cargan hasta que el metodo resolve de la autenticación se ejecuta
> Autenticación basada en metodo resolve

- app/assets/javascripts/app.js
- app/assets/javascripts/application.js
- app/assets/partials/profile_partial.why.html
Se corrigió el uso de moment para la creación de fechas
#32508443941636
> H3-T1: Mis metas (frontend)

- app/assets/javascripts/controllers/LoginController.js
Ahora al registrar al usuario se envia el id del upline
#29979592881800
> H1-T5: Registro (frontend)

- app/controllers/registrations_controller.rb
- app/controllers/tests_controller.rb
- app/models/test.rb
- config/routes.rb
- spec/controllers/requests_controller_spec.rb
- spec/controllers/tests_controller_spec.rb
> Refactor de servicios en Tests

- app/controllers/tests_controller.rb
- spec/controllers/tests_controller_spec.rb
> Corrección en un parámetro de los servicios

- app/assets/javascripts/controllers/ListController.js
- app/assets/partials/business_partial.list.html
Se validó la forma de creación y edición de contactos
#33847423682050
> H9-T1 Lista de contactos (frontend)

- app/assets/javascripts/services/TestService.js
Se actualizó el servicio qe obtiene los resultados, de POST a GET
#32719310290965
> H5-T1: Test de personalidad (frontend)

- app/assets/javascripts/app.js
- app/assets/javascripts/controllers/GlobalMenuController.js
- app/assets/javascripts/services/AuthService.js
- app/assets/javascripts/services/SessionService.js
- app/assets/templates/common/_inner_top_nav_template.html
Se agregó el logout al menu principal
#33842051025907
> H1-T10: Logout

- app/models/test.rb
- app/models/user.rb
- app/views/devise/sessions/create.json.jbuilder
- app/views/users/downlines.json.jbuilder
> H2-T5: Mostrar info de downlines en Ciclo #34208438726825

- app/views/devise/sessions/create.json.jbuilder
- app/views/tests/by_code_and_user.json.jbuilder
- app/views/tests/by_user.json.jbuilder
- app/views/users/downlines.json.jbuilder
A nivel servicios ya regresa textos en español
Diego
> H5-T4: Cambiar textos de inglés a español #34257478475860

- app/views/devise/sessions/create.json.jbuilder
- app/views/users/downlines.json.jbuilder
- Corrección de error en json
Diego
> H2-T5: Mostrar info de usuario y de downlines en Ciclo #34208438726825

- app/views/devise/sessions/create.json.jbuilder
- app/views/users/downlines.json.jbuilder
> H2-T6: Agregar propiedad a servicio #34450714772515

- app/assets/partials/login.html
Se borró el botón para solicitar una invitación
#34450714772477
> H1-T10: Quitar botón para solicitar invitación

- app/assets/javascripts/app.js
- app/assets/javascripts/application.js
- app/assets/javascripts/controllers/FAQController.js
- app/assets/partials/faq.html
- app/assets/templates/common/_inner_top_nav_template.html
- app/models/asset.rb
- config/routes.rb
- db/seeds.rb
Se quitó el FAQ del menú y ahora es un documento que está en los assets.
#34450714772485
> H10-T4: Reubicar FAQ

- app/assets/javascripts/controllers/CycleController.js
- app/assets/javascripts/services/UserService.js
- app/assets/partials/business_partial.cycle.html
- app/assets/partials/system_partial.document.html
- app/assets/stylesheets/modules/_cycle.sass
Se agregó información de los usuarios
#34208438726825
> H2-T5: Mostrar info de usuario y de downlines en Ciclo

- app/assets/javascripts/controllers/CollageController.js
- app/assets/javascripts/services/CollageService.js
- app/assets/partials/profile_partial.collage.html
Se conectaron los servicios que obtienen, guardan y eliminan las imagenes del collage
#33465264557018
> H4-T2 Recuperar imágenes del servidor y mostrarlas en orden

- app/assets/javascripts/application.js
- app/assets/javascripts/controllers/ProfileController.js
- app/assets/javascripts/services/ProfileService.js
- app/assets/partials/login.html
- app/assets/partials/profile_partial.profile.html
- app/assets/stylesheets/modules/_profile.sass
Se conectaron los servicios de actualización de perfil y de contraseña
#33847423682054
> H7-T1 Perfil de usuario (frontend)

- app/assets/partials/faq.html
Se ajustó el diseño del FAQ
#33723807296331
> H10-T1 Secciones fijas (frontend)

- app/assets/javascripts/services/CollageService.js
- app/assets/partials/profile_partial.collage.html
- app/assets/stylesheets/modules/_collage.sass
Se agregó diseño al boton y se corrigieron los bricks repetidos
#33465264557012
> H4-T1 Plugin collage (frontend)

- app/assets/javascripts/services/EventService.js
- app/assets/partials/business_partial.cycle.html
- app/assets/stylesheets/modules/_cycle.sass
Se agregó la imagen en los downlines dentro de la sección de ciclo
#35829574516571
> Bug: no muestra mi foto de perfil al actualizarla

- app/assets/javascripts/app.js
- app/assets/javascripts/controllers/ProfileTestController.js
- app/assets/javascripts/directives/DownlineListDirective.js
- app/assets/partials/profile_partial.test.html
- app/assets/stylesheets/_base.sass
- app/assets/stylesheets/common/_variables.sass
> H5-T7: Agregar la explicación de los colores

- app/assets/javascripts/app.js
- app/assets/javascripts/application.js
- app/assets/javascripts/bower_components/angular-moment/angular-moment.js
- app/assets/javascripts/controllers/ProfileController.js
- app/assets/partials/profile_partial.profile.html
- app/assets/stylesheets/modules/_profile.sass
2. Consultar info de pago: en Preferencias, que puedan ver cuando vence su acceso
> H6-T2: Servicios de pago

- app/assets/partials/login.html
- app/assets/stylesheets/modules/_login.sass
- app/assets/stylesheets/modules/_plan.sass
- Checkbox en register
- Video del plan
#34450714772506
> Mobile version
